export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  CITY_ADMIN = "CITY_ADMIN",
  DEPT_OFFICER = "DEPT_OFFICER",
  PUBLIC = "PUBLIC",
}
export enum City {
  ADAMA = "ADAMA",
  AURORA = "AURORA",
}
export enum Department {
  CITY_ADMINISTRATION = "CITY_ADMINISTRATION",
  TRANSPORT = "TRANSPORT",
  URBAN_DEVELOPMENT = "URBAN_DEVELOPMENT",
  CONSTRUCTION = "CONSTRUCTION",
  WATER_SANITATION = "WATER_SANITATION",
  EDUCATION = "EDUCATION",
  HEALTH = "HEALTH",
  COMMUNICATION = "COMMUNICATION",
  ENVIRONMENT = "ENVIRONMENT",
  PARKS_AND_GREEN_SPACES = "PARKS_AND_GREEN_SPACES",
}