export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  CITY_ADMIN = "CITY_ADMIN",
  DEPT_OFFICER = "DEPT_OFFICER"
}
export enum City {
  ADAMA = "ADAMA",
  AURORA = "AURORA",
}
export enum Department {
  CITY_ADMINISTRATION = "CITY_ADMINISTRATION",
  TRANSPORT = "TRANSPORT",
  URBAN_DEVELOPMENT = "URBAN_DEVELOPMENT",
  CONSTRUCTION = "CONSTRUCTION",
  WATER_SANITATION = "WATER_SANITATION",
  EDUCATION = "EDUCATION",
  HEALTH = "HEALTH",
  COMMUNICATION = "COMMUNICATION",
  ENVIRONMENT = "ENVIRONMENT",
  PARKS_AND_GREEN_SPACES = "PARKS_AND_GREEN_SPACES",
}
export enum ProjectStatus {
  PROPOSED = 'PROPOSED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PLANNED = 'PLANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  DELAYED = 'DELAYED',
  COMPLETED = 'COMPLETED',
}

export enum Priority {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum MilestoneStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  DELAYED = 'DELAYED',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
}

export enum TaskPriority {
  URGENT = 'URGENT',
  HIGH = "HIGH",
  NORMAL = 'NORMAL',
  LOW = 'LOW',
}

export enum IssueStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
}

export enum IssueSeverity {
  CRITICAL = 'CRITICAL',
  MAJOR = 'MAJOR',
  MINOR = 'MINOR',
}

export enum Responsible {
  ADAMA = 'ADAMA',
  SHEGER = 'AURORA',
  BOTH = 'BOTH'
}

export enum DocumentCategory {
  LEGAL = 'LEGAL',
  PROJECT = 'PROJECT',
  MEETING = 'MEETING',
  FINANCIAL = 'FINANCIAL',
  POLICY = 'POLICY',
  EVIDENCE = 'EVIDENCE',
  ARCHIVE = 'ARCHIVE',
}

export enum AccessLevel {
  PUBLIC = 'PUBLIC',
  BOTH_CITIES = 'BOTH_CITIES',
  OWN_CITY_ONLY = 'OWN_CITY_ONLY',
  DEPARTMENT_ONLY = 'DEPARTMENT_ONLY',
  ADMINS_ONLY = 'ADMINS_ONLY',
}

export enum DocumentApprovalStatus {
  DRAFT = 'DRAFT',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED'
}
export enum MessageType {
  REQUEST = 'REQUEST',
  RESPONSE = 'RESPONSE',
  NOTIFICATION = 'NOTIFICATION',
  INQUIRY = 'INQUIRY',
  COMPLAINT = 'COMPLAINT',
  INVITATION = 'INVITATION',
  APPROVAL = 'APPROVAL',
  REJECTION = 'REJECTION',
}

export enum MessagePriority {
  NORMAL = 'NORMAL',
  URGENT = 'URGENT',
  CRITICAL = 'CRITICAL',
}

export enum MessageStatus {
  SENT = 'SENT',
  READ = 'READ',
  REPLIED = 'REPLIED',
  ESCALATED = 'ESCALATED',
  CLOSED = 'CLOSED',
}
export enum EventType {
  WORKSHOP = 'WORKSHOP',
  OFFICIAL_VISIT = 'OFFICIAL_VISIT',
  CULTURAL_EXCHANGE = 'CULTURAL_EXCHANGE',
  INVESTMENT_FORUM = 'INVESTMENT_FORUM',
  COMMITTEE_MEETING = 'COMMITTEE_MEETING',
  TRAINING = 'TRAINING',
  CEREMONY = 'CEREMONY',
}

export enum EventStatus {
  UPCOMING = 'UPCOMING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ExpenditureStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ExpenditureCategory {
  PERSONNEL = 'PERSONNEL',
  MATERIALS = 'MATERIALS',
  TRANSPORT = 'TRANSPORT',
  ADMINISTRATION = 'ADMINISTRATION',
  CONTINGENCY = 'CONTINGENCY',
  OTHER = 'OTHER',
}

export enum EquipmentStatus {
  AVAILABLE = 'AVAILABLE',
  IN_USE = 'IN_USE',
  RETURNED = 'RETURNED',
  DAMAGED = 'DAMAGED',
}