export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  CITY_ADMIN = "CITY_ADMIN",
  DEPT_OFFICER = "DEPT_OFFICER"
}
export enum City {
  ADAMA = "ADAMA",
  AURORA = "AURORA",
}
export enum Department {
  CITY_ADMINISTRATION = "CITY_ADMINISTRATION",
  TRANSPORT = "TRANSPORT",
  URBAN_DEVELOPMENT = "URBAN_DEVELOPMENT",
  CONSTRUCTION = "CONSTRUCTION",
  WATER_SANITATION = "WATER_SANITATION",
  EDUCATION = "EDUCATION",
  HEALTH = "HEALTH",
  COMMUNICATION = "COMMUNICATION",
  ENVIRONMENT = "ENVIRONMENT",
  PARKS_AND_GREEN_SPACES = "PARKS_AND_GREEN_SPACES",
}
export enum ProjectStatus {
  PROPOSED = 'PROPOSED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PLANNED = 'PLANNED',
  IN_PROGRESS = 'IN_PROGRESS',
  ON_HOLD = 'ON_HOLD',
  DELAYED = 'DELAYED',
  COMPLETED = 'COMPLETED',
}

export enum Priority {
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum MilestoneStatus {
  NOT_STARTED = 'NOT_STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  DELAYED = 'DELAYED',
}

export enum TaskStatus {
  TODO = 'TODO',
  IN_PROGRESS = 'IN_PROGRESS',
  DONE = 'DONE',
}

export enum TaskPriority {
  URGENT = 'URGENT',
  HIGH = "HIGH",
  NORMAL = 'NORMAL',
  LOW = 'LOW',
}

export enum IssueStatus {
  OPEN = 'OPEN',
  IN_PROGRESS = 'IN_PROGRESS',
  RESOLVED = 'RESOLVED',
}

export enum IssueSeverity {
  CRITICAL = 'CRITICAL',
  MAJOR = 'MAJOR',
  MINOR = 'MINOR',
}

export enum Responsible {
  ADAMA = 'ADAMA',
  SHEGER = 'AURORA',
  BOTH = 'BOTH'
}
//document enums
export enum DocumentCategory {
  LEGAL = 'LEGAL',
  PROJECT = 'PROJECT',
  MEETING = 'MEETING',
  FINANCIAL = 'FINANCIAL',
  POLICY = 'POLICY',
  EVIDENCE = 'EVIDENCE',
  ARCHIVE = 'ARCHIVE',
}

export enum AccessLevel {
  PUBLIC = 'PUBLIC',
  BOTH_CITIES = 'BOTH_CITIES',
  OWN_CITY_ONLY = 'OWN_CITY_ONLY',
  DEPARTMENT_ONLY = 'DEPARTMENT_ONLY',
  ADMINS_ONLY = 'ADMINS_ONLY',
}

export enum DocumentApprovalStatus {
  DRAFT = 'DRAFT',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED'
}
//message enums
export enum MessageType {
  REQUEST = 'REQUEST',
  RESPONSE = 'RESPONSE',
  NOTIFICATION = 'NOTIFICATION',
  INQUIRY = 'INQUIRY',
  COMPLAINT = 'COMPLAINT',
  INVITATION = 'INVITATION',
  APPROVAL = 'APPROVAL',
  REJECTION = 'REJECTION',
}

export enum MessagePriority {
  NORMAL = 'NORMAL',
  URGENT = 'URGENT',
  CRITICAL = 'CRITICAL',
}

export enum MessageStatus {
  SENT = 'SENT',
  READ = 'READ',
  REPLIED = 'REPLIED',
  ESCALATED = 'ESCALATED',
  CLOSED = 'CLOSED',
}
//event enums
export enum EventType {
  WORKSHOP = 'WORKSHOP',
  OFFICIAL_VISIT = 'OFFICIAL_VISIT',
  CULTURAL_EXCHANGE = 'CULTURAL_EXCHANGE',
  INVESTMENT_FORUM = 'INVESTMENT_FORUM',
  COMMITTEE_MEETING = 'COMMITTEE_MEETING',
  TRAINING = 'TRAINING',
  CEREMONY = 'CEREMONY',
}

export enum EventStatus {
  UPCOMING = 'UPCOMING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum ExpenditureStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum ExpenditureCategory {
  PERSONNEL = 'PERSONNEL',
  EQUIPMENT = 'EQUIPMENT',
  MATERIALS = 'MATERIALS',
  TRAVEL = 'TRAVEL',
  SERVICES = 'SERVICES',
  INFRASTRUCTURE = 'INFRASTRUCTURE',
  OTHER = 'OTHER',
}

export enum EquipmentStatus {
  AVAILABLE = 'AVAILABLE',
  IN_USE = 'IN_USE',
  RETURNED = 'RETURNED',
  DAMAGED = 'DAMAGED',
  REPAIRED = 'REPAIRED',
}
//news enums
export enum NewsCategory {
  ACHIEVEMENT = 'ACHIEVEMENT',
  NEW_AGREEMENT = 'NEW_AGREEMENT',
  PROJECT_UPDATE = 'PROJECT_UPDATE',
  EVENT_ANNOUNCEMENT = 'EVENT_ANNOUNCEMENT',
  JOINT_STATEMENT = 'JOINT_STATEMENT',
  CULTURAL_HIGHLIGHT = 'CULTURAL_HIGHLIGHT',
}

export enum NewsApprovalStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum NewsPostedByCity {
  ADAMA = 'ADAMA',
  SHEGER = 'AURORA',
  JOINT = 'JOINT',
}
//notification enums
export enum NotificationType {
  MESSAGE_RECEIVED = 'MESSAGE_RECEIVED',
  DOCUMENT_UPLOADED = 'DOCUMENT_UPLOADED',
  MILESTONE_DELAYED = 'MILESTONE_DELAYED',
  TASK_DUE = 'TASK_DUE',
  EVENT_REMINDER = 'EVENT_REMINDER',
  BUDGET_ALERT = 'BUDGET_ALERT',
  PROJECT_APPROVED = 'PROJECT_APPROVED',
  PROJECT_REJECTED = 'PROJECT_REJECTED',
  ESCALATION = 'ESCALATION',
}
export enum NotificationPriority {
  NORMAL = 'NORMAL',
  URGENT = 'URGENT',
  CRITICAL = 'CRITICAL',
}
// Report Enums 
export enum ReportType {
  PARTNERSHIP_PROGRESS = 'PARTNERSHIP_PROGRESS',
  PROJECT_COMPLETION = 'PROJECT_COMPLETION',
  COMMUNICATION_ACTIVITY = 'COMMUNICATION_ACTIVITY',
  BUDGET_UTILIZATION = 'BUDGET_UTILIZATION',
  DOCUMENT_ACTIVITY = 'DOCUMENT_ACTIVITY',
}

export enum ReportCity {
  ADAMA = 'ADAMA',
  AURORA = 'AURORA',
  BOTH = 'BOTH',
}